@echo off
echo ÿ   W O R L D    W A R     2     in  E U R O P E
echo                       Strategy Game
echo ÿ
echo ========================================================================
echo ÿ
echo WW2 to play the game
echo see file README.TXT for latest information
echo INSTALL to load on hard drive
echo Documentation is in the file WW2.DOC
echo PRINTDOC to print documentation
echo Online help available within the game
echo ÿ
echo ========================================================================
echo ÿ
echo Hit Ctrl-C if you do NOT wish to begin the game
pause Press ENTER to begin World War 2 in Europe
cls
echo Loading World War 2 in Europe ...
ww2.exe
