ECHO OFF
pallete.exe
talksb register.voc
if errorlevel 1 tlk register.pc
cls

echo YOU ARE OBLIGATED TO REGISTER THIS GAME AFTER THE 30 DAY EVALUATION PERIOD.
echo  REGISTER, AND YOU GET:
echo    - The rest of the game.
echo    - A customizable Boss Key.
echo    - A Microsoft Windows(TM) Icon and PIF file.
echo    - Super cheat codes.
echo off
echo   SUPPORT THE SPIRIT OF SHAREWARE! REGISTER THIS GAME!!(Read DIEBARNY.DOC)
echo                  Got problems or questions? Read DIEBARNY.DOC
echo                        Thank you for playing DIEBLARNEY!


