ECHO OFF
pal.exe
talksb register.voc
if errorlevel 1 tlk register.pc
cls

echo YOU ARE OBLIGATED TO REGISTER THIS GAME AFTER THE 30 DAY EVALUATION PERIOD.
echo There are two levels of registration: GOLD and PLATINUM (Read XBLASTER.DOC) 
echo  REGISTER *GOLD*, and you get:
echo    - The rest of the game.
echo    - A printed manual with hints and strategies for beating the game.
echo    - A customizable Boss Key.
echo    - A Microsoft Windows(TM) Icon and PIF file.  
echo    - Super cheat codes.
echo off
echo  REGISTER *PLATINUM*, and you get:
echo    - All the above, plus:
echo    - Lifetime software support. (*GOLD* registrants only get 90 days support)
echo    - An advanced customizable Boss Key.
echo    - Program ADD-ONS that alter graphics/gameplay/ect. to extend gameplay value.
echo off
echo    SUPPORT THE SPIRIT OF SHAREWARE! REGISTER THIS GAME!!(Read XBLASTER.DOC)
echo                  Got problems or questions? Read XBLASTER.DOC
echo                        Thank you for playing Xenoblaster!


